publication_top_name: "General Pharmaceutical Services"
publication_sub_name: " England 2015/16 to 2023/24"
publication_date: "10 October 2024"
responsible_statistician: "Kirsty Gray"
fy_excel_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/gphs/gps_2324_summary_tables_v001.xlsx"
background_link: "https://nhsbsa-opendata.s3.eu-west-2.amazonaws.com/gphs/gphs_background_v001.html"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
